@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjM2MzYyODk1LCJleHAiOjE2MzYzNjQ2OTV9.JALiOgUGbrUsz-utODevCC6Hkjr8z_hQcqYIVa1rATw

### POST /login
# copy to token given and paste into Authorization: {token} for /users endpoint
POST http://localhost:3033/login
content-type: application/json

{
    "username" : "imi",
    "password" : "loveDaddy3"
}

### POST /register
POST http://localhost:3033/register
content-type: application/json

{
    "username" : "newb",
    "email" : "newb@rudyah.com",
    "password" : "newPass"
}

### GET /users
# send with a token (text after 'Authorization:') received from running a post to /login
GET http://localhost:3033/users
content-type: application/json
Authorization: Bearer {{token}}


### GET /products
GET http://localhost:3033/products

### GET /products
GET http://localhost:3033/products?brand_id=1

### GET /products
GET http://localhost:3033/products?category_id=3

### GET /product/brands
GET http://localhost:3033/product/brands

### GET /product/categories
GET http://localhost:3033/product/categories



### GET /user/favorites
GET http://localhost:3033/user/favorites
content-type: application/json
Authorization: Bearer {{token}}

### POST /user/favorite
# this will just return whatever is in the request body
POST http://localhost:3033/user/favorite
content-type: application/json
Authorization: Bearer {{token}}

{
    "note": "feel good food mmmmm", 
    "product_id": 1
}

### PUT /user/favorite/:id
PUT http://localhost:3033/user/favorite/2
content-type: application/json
Authorization: Bearer {{token}}

{
    "note": "feel good food; mmmmm mmmm good"
}

### DELETE /user/favorite/:id
DELETE http://localhost:3033/user/favorite/2
content-type: application/json
Authorization: Bearer {{token}}



